services:
    codekeepr.registration:
        class: Frigg\KeeprBundle\EventListener\RegistrationListener
        arguments: [@router]
        tags:
            - { name: kernel.event_subscriber }

    codekeepr.activity:
        class: Frigg\KeeprBundle\EventListener\ActivityListener
        arguments: [@service_container]
        tags:
            - { name: doctrine.event_listener, event: postPersist, method: postPersist }
            - { name: doctrine.event_listener, event: postUpdate, method: postUpdate }

    codekeepr.twig.user_extension:
        class: Frigg\KeeprBundle\Twig\UserExtension
        tags:
            - { name: twig.extension }

