parameters:
    codekeepr.config: "%kernel.root_dir%/../src/Frigg/KeeprBundle/Resources/config/codekeepr.yml"
    codekeepr.registration.class: Frigg\KeeprBundle\EventListener\RegistrationListener
    codekeepr.activity.class: Frigg\KeeprBundle\EventListener\ActivityListener
    codekeepr.post.service.class: Frigg\KeeprBundle\Service\PostService
    codekeepr.post.twig.class: Frigg\KeeprBundle\Twig\PostExtension
    codekeepr.post.voter.class: Frigg\KeeprBundle\Security\Voter\PostVoter
    codekeepr.user.voter.class: Frigg\KeeprBundle\Security\Voter\UserVoter


services:

    # buisness services
    codekeepr.post.service:
        class: %codekeepr.post.service.class%
        arguments: [ @doctrine.orm.entity_manager, @security.context, %codekeepr.config% ]


    # event listeners
    codekeepr.registration:
        class: %codekeepr.registration.class%
        arguments: [@router]
        tags:
            - { name: kernel.event_subscriber }

    codekeepr.activity:
        class: %codekeepr.activity.class%
        arguments: [@service_container]
        tags:
            - { name: doctrine.event_listener, event: postPersist, method: postPersist }
            - { name: doctrine.event_listener, event: postUpdate, method: postUpdate }

    # twig extensions
    codekeepr.post.twig:
        class: %codekeepr.post.twig.class%
        arguments: [@codekeepr.post.service]
        tags:
            - { name: twig.extension }

    # voters
    codekeepr.post.voter:
        class: %codekeepr.post.voter.class%
        public: false
        arguments:
            - @doctrine.orm.entity_manager
        tags:
            - { name: security.voter }

    codekeepr.user.voter:
        class: %codekeepr.user.voter.class%
        public: false
        arguments:
            - @doctrine.orm.entity_manager
        tags:
            - { name: security.voter }
