parameters:
    codekeepr.config: "%kernel.root_dir%/../src/Frigg/KeeprBundle/Resources/config/codekeepr.yml"
    codekeepr.registration.class: Frigg\KeeprBundle\EventListener\RegistrationListener
    codekeepr.listener.identifier.class: Frigg\KeeprBundle\EventListener\SanitizeIdentifierListener
    codekeepr.post.twig.class: Frigg\KeeprBundle\Twig\PostExtension
    codekeepr.post.voter.class: Frigg\KeeprBundle\Security\Voter\PostVoter
    codekeepr.user.twig.class: Frigg\KeeprBundle\Twig\UserExtension
    codekeepr.user.voter.class: Frigg\KeeprBundle\Security\Voter\UserVoter
    codekeepr.user.search.class: Frigg\KeeprBundle\Twig\SearchExtension
    codekeepr.ouath.user.provider.class: Frigg\KeeprBundle\Security\OAuth\OAuthUserProvider
    codekeepr.elastica.query.builder.class: Frigg\KeeprBundle\Elastica\QueryBuilder

services:
    # services
    codekeepr.oauth.user.provider.service:
        class: %codekeepr.ouath.user.provider.class%
        arguments: ['@fos_user.user_manager', { github: github_id }]

    codekeepr.elastica.query.builder:
        class: %codekeepr.elastica.query.builder.class%
        arguments: []

    # event listeners
    codekeepr.registration:
        class: %codekeepr.registration.class%
        arguments: [@router]
        tags:
            - { name: kernel.event_subscriber }

    codekeepr.listener.identifier:
        class: %codekeepr.listener.identifier.class%
        tags:
            - { name: doctrine.event_listener, event: prePersist, method: prePersist }
            - { name: doctrine.event_listener, event: preUpdate, method: preUpdate }

    # twig extensions
    codekeepr.post.twig:
        class: %codekeepr.post.twig.class%
        arguments: [@doctrine.orm.entity_manager, @security.context]
        tags:
            - { name: twig.extension }

    codekeepr.user.twig:
        class: %codekeepr.user.twig.class%
        arguments: [@doctrine.orm.entity_manager, @security.context]
        tags:
            - { name: twig.extension }

    codekeepr.search.twig:
        class: %codekeepr.user.search.class%
        tags:
            - { name: twig.extension }
    # voters
    codekeepr.post.voter:
        class: %codekeepr.post.voter.class%
        public: false
        arguments:
            - @doctrine.orm.entity_manager
        tags:
            - { name: security.voter }

    codekeepr.user.voter:
        class: %codekeepr.user.voter.class%
        public: false
        arguments:
            - @doctrine.orm.entity_manager
        tags:
            - { name: security.voter }
