security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username_email

    firewalls:
        secured_area:
            anonymous: ~
            logout: true
            remember_me:
                key: %secret%
                always_remember_me: true
            form_login:
                provider: fos_userbundle
                csrf_provider: form.csrf_provider
                target_path_parameter: /
                always_use_default_target_path: true
                remember_me: true
            oauth:
                resource_owners:
                    github: "/login/check-github"
                    google: "/login/check-google"
                    reddit: "/login/check-reddit"
                login_path: /login
                use_forward: false
                failure_path: /login
                oauth_user_provider:
                    service: codekeepr.oauth.user.provider.service
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_provider: form.csrf_provider
                target_path_parameter: /
                always_use_default_target_path: true
                remember_me: true
            remember_me:
                key: %secret%
            logout: true
            anonymous: true

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, role: IS_AUTHENTICATED_ANONYMOUSLY }
