#!/usr/bin/env ruby
# post-receive

from, to, branch = ARGF.read.split " "

if (branch =~ /master$/) == nil
    puts "Received branch #{branch}, not deploying."
    exit
end

puts "Codekeepr: Deploying master"

deploy_to_dir = File.expand_path('../www')

puts "Exporting master(#{to}) to '#{deploy_to_dir}'"

`GIT_WORK_TREE="#{deploy_to_dir}" git checkout -f master`

puts "Performing post deployment procedures"

Dir.chdir("#{deploy_to_dir}")

`#{"cp web/.htaccess_prod web/.htaccess" +
" && php app/console cache:clear --env=prod --no-debug  --no-interaction" +
" && php app/console assetic:dump --env=prod --no-debug --no-interaction"}`

puts "Done."
