#!/usr/bin/env ruby

from, to, branch = ARGF.read.split " "

if (branch =~ /master$/) == nil
    puts "Received branch #{branch}, not deploying"
    exit
end

target = File.expand_path("../www")

puts "Deploying #{branch}"

puts "Exporting #{to} to #{target}"

`GIT_WORK_TREE="#{target}" git checkout -f #{branch}`

puts "Post-deployment procedures"

Dir.chdir("#{target}")

`cp web/.htaccess_prod web/.htaccess`
`php app/console cache:clear --env=prod --no-debug  --no-interaction`
`php app/console assetic:dump --env=prod --no-debug --no-interaction`

puts "Done"

